---
title: DevTech Systems, Inc.
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  careers:
    title: Careers
    output: true
  contracting-vehicles:
    title: Contracting Vehicles
    output: false
    permalink: "/:collection/:path/"
  posts:
    title: Insights
    output: true
  our-team:
    title: Management Team
    output: true
  news:
    title: News
    output: true
  office-locations:
    title: Office Locations
    output: false
  our-practices:
    title: Practice Areas
    output: true
    permalink: "/our-practices/:title"
    Headline: Headline would go here
    Brief Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
      urna diam, facilisis eu ante nec, mattis aliquam nulla. Orci varius natoque
      penatibus et.
  projects:
    title: Projects
    output: true
  publications:
    title: Publications
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    Title: 
    Highlight: 
    Banner Image: 
    layout: page
- scope:
    path: ''
    type: posts
  values:
    permalink: "/insights/:year/:month/:day/:title/"
    Practice Area:
    - 
    Teaser Image: 
    Banner Image: 
    Highlight: 
    Category: 
    Author: 
    layout: post
- scope:
    path: ''
    type: news
  values:
    permalink: "/news/:year/:month/:day/:title/"
    Banner Image: 
    Highlight: 
    Category: 
    layout: news
- scope:
    path: ''
    type: authors
  values:
    Author Image: 
    Author Title: 
    layout: page
- scope:
    path: ''
    type: careers
  values:
    Title: 
    Highlight: 
    Location: 
    Type: Full time
    Department: 
    Experience: 
    Application Link: 
    navigation_group: Careers
    layout: page
- scope:
    path: ''
    type: contracting-vehicles
  values:
    Full Title: 
    Agency: 
    Is Prime Contract: 
    layout: page
- scope:
    path: ''
    type: our-team
  values:
    Title: 
    Highlight: 
    Headshot Image: 
    Job Title: 
    navigation_group: Our Team
    layout: page
- scope:
    path: ''
    type: practice-areas
  values:
    Highlight: 
    Preview/Teaser Image: 
    Detail Page Image: 
    Light Icon Image: 
    Dark Icon Image: 
    layout: practice-areas
- scope:
    path: ''
    type: reports-and-publications
  values:
    Document Link Title: 
    Document Region: 
    Year Published: 
    Mission Title: 
    Document URL: 
    Practice Area:
    - 
    layout: page
- scope:
    path: ''
    type: projects
  values:
    Title: 
    Highlight: 
    Banner Image: 
    Practice Area:
    - 
    Region: 
    Is Active: 
    layout: project
- scope:
    path: ''
    type: office-locations
  values:
    Address Text: ''
    Location Image: 
    Phone Number: 
    layout: page
newEmptyArray: []
email: ''
description: 'We are dedicated to data-driven solutions that build capacity,  strengthen
  partnerships, and address complex policy challenges.

'
baseurl: ''
url: ''
permalink: pretty
