---
title: DevTech Systems, Inc.
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  careers:
    title: Careers
    output: true
  contracting-vehicles:
    title: Contracting Vehicles
    output: false
    permalink: "/:collection/:path/"
  posts:
    title: Insights
    output: true
  our-team:
    title: Management Team
    output: true
  practice-areas:
    title: Practice Areas
    output: true
    permalink: "/:collection/:title"
    Headline: Headline would go here
    Brief Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
      urna diam, facilisis eu ante nec, mattis aliquam nulla. Orci varius natoque
      penatibus et.
  reports-and-publications:
    title: Reports & Publications
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    Title: 
    Highlight:
    Banner Image: 
    layout: page
- scope:
    path: ''
    type: posts
  values:
    permalink: "/insights/:year/:month/:day/:title/"
    Practice Area:
    - 
    Banner Image: 
    Highlight: 
    Author: 
    layout: post
- scope:
    path: ''
    type: authors
  values:
    Author Image: 
    Author Title: 
    layout: page
- scope:
    path: ''
    type: careers
  values:
    Organization: 
    Location:
      City: 
      State: 
    Type of Opportunity: Full time
    layout: page
- scope:
    path: ''
    type: contracting-vehicles
  values:
    Full Title: 
    Agency: 
    Prime Contract?: 
    layout: page
- scope:
    path: ''
    type: our-team
  values:
    Headshot Image: 
    layout: page
- scope:
    path: ''
    type: reports-and-publications
  values:
    Document Link Title: 
    Document Region: 
    Year Published: 
    Mission Title: 
    Document URL: 
    Practice Area:
    - 
    layout: page
email: ''
description: 'We are dedicated to data-driven solutions that build capacity,  strengthen
  partnerships, and address complex policy challenges.

'
baseurl: ''
url: ''
permalink: pretty
