---
title: DevTech Systems, Inc.
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  contracting-vehicles:
    title: Contracting Vehicles
    output: true
    permalink: "/about/:collection/:path/"
  insights:
    title: Insights
    output: true
    permalink: "/:collection/:title/"
  our-team:
    title: Management Team
    output: true
  posts:
    title: Posts
    output: true
  practice-areas:
    title: Practice Areas
    output: true
    permalink: "/:collection/:title"
    Headline: Headline would go here
    Brief Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
      urna diam, facilisis eu ante nec, mattis aliquam nulla. Orci varius natoque
      penatibus et.
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: insights
    type: posts
  values:
    Practice Area:
    - 
    Banner Image: 
    Introduction Text: 
    Author: 
    layout: post
- scope:
    path: ''
    type: authors
  values:
    Author Image: 
    Author Title: 
    layout: page
- scope:
    path: ''
    type: pages
  values:
    layout: page
    Author Image: 
    Author Title: 
email: ''
description: 'We are dedicated to data-driven solutions that build capacity,  strengthen
  partnerships, and address complex policy challenges.

'
baseurl: ''
url: ''
permalink: pretty
