---
# Site settings
title: "DevTech Systems, Inc."
email: ""
timezone: UTC
description: > # this means to ignore newlines until "baseurl:"
  We are dedicated to data-driven solutions that build capacity, 
  strengthen partnerships, and address complex policy challenges.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  our-team:
    title: Management Team
    output: true
  posts:
    title: Posts
    output: true
  practice-areas:
    title: Practice Areas
    output: true
    permalink: /:collection/:title
    Headline: Headline would go here
    Brief Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
      urna diam, facilisis eu ante nec, mattis aliquam nulla. Orci varius natoque
      penatibus et.
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
